### ISSUE TITLE
Error reported when generating: RuntimeError: CUDA error

### ISSUE THREAD

**Issue by luogyix** [githubcto/FramePack-ZLUDA#1]
Running on rx7900xtx gpu，
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

![Image](https://github.com/user-attachments/assets/d323bbe1-334f-4744-b9c4-604f791f5d4a)

**Comment by THEGOBBLER** [comment]
I had this and it was because I didn't successfully copy the .dlls from the .zluda folder to the torch lib folders (manually installed then downloaded and ran the batch file in download.zip which didn't complete because it already detected a venv).

I fixed it the lazy way by getting the download.zip then making a new .bat file with just the lines after del zluda.zip in the install-win-zluda.bat, it ran and completed the correct replacements/renames.

**Comment by luogyix** [comment]
第一步：
    https://github.com/lshqqytiger/ZLUDA/releases/
    选择对应的rocm版本，下载zluda压缩包并解压

![Image](https://github.com/user-attachments/assets/91cbf151-70be-4cbf-843d-c19f97fac975)
第二步：
    将第一步中的zluda文件夹下的 
        cublas.dll cusparse.dll cufft.dll cufftw.dll nvrtc.dll
    五个文件复制到项目的 venv\Lib\site-packages\torch\lib文件夹下
第三步：
    将zluda文件夹路径添加到系统环境变量

![Image](https://github.com/user-attachments/assets/8a6c9f50-7d1c-45b8-9f7e-89e0231784a4)
第四步：
  启动后运行，生成视频，可以解锁新的报错，仍在解决中

![Image](https://github.com/user-attachments/assets/81a3dd3a-3c0f-4498-850d-a53cad0caf26)

**Comment by luogyix** [comment]
备份venv\Lib\site-packages\torch\lib下的cublas64_11.dll和cusparse64_11.dll，把复制过去的cublas.dll重命名为cublas64_11.dll 把cusparse.dll重命名为cusparse64_11.dll

**Comment by quanzs538** [comment]
> 备份venv\Lib\site-packages\torch\lib下的cublas64_11.dll和cusparse64_11.dll，把复制过去的cublas.dll重命名为cublas64_11.dll 把cusparse.dll重命名为cusparse64_11.dll

FramePack-F1
Traceback (most recent call last):
  File "C:\FramePack-ZLUDA\demo_gradio_f1_attention.py", line 16, in <module>
    print(f"GPU: {torch.cuda.get_device_name()}")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FramePack-ZLUDA\venv\Lib\site-packages\torch\cuda\__init__.py", line 544, in get_device_name
    return get_device_properties(device).name
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\FramePack-ZLUDA\venv\Lib\site-packages\torch\cuda\__init__.py", line 576, in get_device_properties
    _lazy_init()  # will define _get_device_properties
    ^^^^^^^^^^^^
  File "C:\FramePack-ZLUDA\venv\Lib\site-packages\torch\cuda\__init__.py", line 372, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 801: operation not supported
请按任意键继续. . .

不成功啊
