### ISSUE TITLE
OSError: [WinError 126] Error loading cudnn64_9.dll - But it's there?

### ISSUE THREAD

**Issue by DenSchiemannski** [githubcto/FramePack-ZLUDA#5]
Getting the following when starting the FramePack-attention.bat:

Traceback (most recent call last):
  File "D:\FramePack-ZLUDA\demo_gradio_attention.py", line 8, in <module>
    import torch
  File "D:\FramePack-ZLUDA\venv\lib\site-packages\torch\__init__.py", line 270, in <module>
    _load_dll_libraries()
  File "D:\FramePack-ZLUDA\venv\lib\site-packages\torch\__init__.py", line 266, in _load_dll_libraries
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "D:\FramePack-ZLUDA\venv\lib\site-packages\torch\lib\cudnn64_9.dll" or one of its dependencies.

I checked and triple checked, the file is there.

**Comment by LaneRendell** [comment]
I also seem to be encountering this.

My error message is _slightly different_

`(venv) C:\Users\CharlesNicholson\Desktop\FramePack-ZLUDA>FramePack-attention.bat
Traceback (most recent call last):
  File "C:\Users\CharlesNicholson\Desktop\FramePack-ZLUDA\demo_gradio_attention.py", line 8, in <module>
    import torch
  File "C:\Users\CharlesNicholson\Desktop\FramePack-ZLUDA\venv\lib\site-packages\torch\__init__.py", line 270, in <module>
    _load_dll_libraries()
  File "C:\Users\CharlesNicholson\Desktop\FramePack-ZLUDA\venv\lib\site-packages\torch\__init__.py", line 266, in _load_dll_libraries
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\CharlesNicholson\Desktop\FramePack-ZLUDA\venv\lib\site-packages\torch\lib\cudnn64_9.dll" or one of its dependencies.`

**Comment by LaneRendell** [comment]
@DenSchiemannski 

I was able to resolve this, I missed downloading the HIP SDK extension:
(latest here linked below)

https://drive.google.com/file/d/1Gvg3hxNEj2Vsd2nQgwadrUEY6dYXy0H9/view?usp=sharing

Unzip that into: C:\Program Files\AMD\ROCm\6.2

Grabbing these (I think I must have originally grabbed an older version): https://github.com/lshqqytiger/ZLUDA/releases/download/rel.5e717459179dc272b7d7d23391f0fad66c7459cf/ZLUDA-nightly-windows-rocm6-amd64.zip

Pasting them into (might not be needed): 
C:\Program Files\AMD\ROCm\6.2\zluda

Then I copied the one's mentioned in the README script
``copy .zluda\cublas.dll venv\Lib\site-packages\torch\lib\cublas64_11.dll /y
copy .zluda\cusparse.dll venv\Lib\site-packages\torch\lib\cusparse64_11.dll /y
copy .zluda\nvrtc.dll venv\Lib\site-packages\torch\lib\nvrtc64_112_0.dll /y
copy .zluda\cudnn.dll venv\Lib\site-packages\torch\lib\cudnn64_9.dll /y``

And manually pasted them into:

FramePack-ZLUDA\venv\Lib\site-packages\torch\lib

And renaming the pasted one's to match the names from the script.

I.e. cublas.dll to cublas64_11.dll

This was all more manual than necessary but I was trying to troubleshoot where I had gone wrong.
